sync_chain: true
tx_pool:
  threads: 2
  address: tcp://127.0.0.1:10011
blockchain:
  threads: 2
  address: tcp://127.0.0.1:10014
  file: ""
  peers:
    - address: tcp://127.0.0.1:10004
metronome:
  threads: 2
  address: tcp://127.0.0.1:10013
