#include "wallet.hpp"

// create SHA256 pub / private key pair
Wallet create_wallet() {
    return {};
}

// load wallet from file
Wallet load_wallet(std::string filepath) {
    return {};
}

// write wallet to file
void store_wallet(std::string filepath, Wallet wallet) {

}

// signature is generated in create_transaction, it should sign all of the other fields in the transaction struct
// the id of the transaction should be unique for each transaction generated by a wallet 
Transaction create_transaction(SHA256Hash src, SHA256Hash dest, uint32_t amount) {
    return {};
}

// should take some command line argument for what to run
// options: create new wallet, get balance, create transaction

int main(int argc, char** argv) {
    printf("Hello, I'm a wallet.\n");

    return 0;
}